PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX vann: <http://purl.org/vocab/vann/> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX : <http://www.lexinfo.net/ontology/3.0/lexinfo#> 
PREFIX terms: <http://purl.org/dc/terms/> 
PREFIX cc: <http://creativecommons.org/ns#> 

SELECT DISTINCT ?class ?super
WHERE {
    ?class rdfs:subClassOf|^rdfs:subClassOf [].
    {   ?class rdfs:subClassOf ?super. 
        FILTER(!isblank(?class))
    } UNION {
        MINUS { ?class rdfs:subClassOf ?super.
            FILTER(!isblank(?class))
        }
    }
    FILTER(! isblank(?class))
    FILTER(! isblank(?super))
} ORDER BY ?class ?super
    